# Generated by Django 5.0.3 on 2024-10-11 01:58

import dl.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("text_content", models.TextField(default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dl.models.custom_upload_to,
                        verbose_name="todo_image",
                    ),
                ),
                ("star", models.BooleanField(default=False)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
