# Generated by Django 5.0.3 on 2024-11-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="time",
            field=models.TextField(default="00:00"),
        ),
    ]
