# Generated by Django 5.0.3 on 2024-11-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dl", "0002_todo_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="time",
            field=models.TextField(default=""),
        ),
    ]
