# Generated by Django 5.0.3 on 2024-11-21 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dl", "0007_alter_todo_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="time",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
