# Generated by Django 5.0.3 on 2024-11-21 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dl", "0010_alter_todo_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
