# Generated by Django 5.0.3 on 2024-11-30 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dl", "0014_user_alter_todo_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
    ]
