# Generated by Django 5.0.3 on 2024-11-30 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dl", "0015_remove_user_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_validate",
        ),
    ]
